version: "3"

services:
  mysql: 
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/server/config/init.sql
    environment: 
      MYSQL_ROOT_PASSWORD: didisuper
      MYSQL_DATABASE: dashboard
      MYSQL_USER: root
      MYSQL_PASSWORD: didisuper
      MYSQL_HOSTNAME: localhost
    ports: 
      - 3307:3306
    expose:
      - 3307
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
      - mysql:mysql
    environment:
      # PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_PASSWORD: didisuper
    restart: always
    ports: 
      - 8899:80
    networks:
      - backend

  web-server:
    container_name: web-server
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - mysql:mysql
    depends_on:
      - mysql
    networks:
      - backend


    # command: ["./wait-for-it.sh", "172.26.0.1:3307", "--", "sh", "run.sh"]
    # environment: 
    #   - DB_HOST=172.26.0.1
    #   - DB_USER=root
    #   - DB_PASS=1234
    #   - NODE_ENV=production

volumes:
  db_data: {}
networks:
  backend:
 