version: "3"

services:
  nginx: 
    container_name: nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - web-server
    depends_on:
      - web-server
      - phpmyadmin
      - mysql
    ports: 
      - 8888:80
    networks:
      - vpn

  mysql: 
    image: mysql:8
    restart: always
    container_name: mysql
    # volumes:
    #   - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 20s
    #   retries: 5
    environment: 
      MYSQL_ROOT_PASSWORD: didiSuper%4F
      MYSQL_DATABASE: dashboard
      MYSQL_USER: root
      MYSQL_PASSWORD: didiSuper%4F

    ports: 
      - 3307:3306
    expose:
      - 3307
    networks:
      - vpn

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_PASSWORD: didiSuper%4F
    restart: always
    ports: 
      - 8899:80
    networks:
      - vpn

  web-server:
    container_name: web-server
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - mysql:mysql
    depends_on:
      - mysql
    networks:
      - vpn
    environment: 
      - NODE_DB_HOST=172.20.0.1
      - NODE_ENV=production
      - DB_PASS=didiSuper%4F
      - DIDI_DB_HOST=170.32.0.196
      - DIDI_DB_USER=newcatuser
      - DIDI_DB_PASS=newcatpwd
      - DIDI_DB_PORT=6033
      - NODE_DB_UESR=root
  
networks:
  vpn:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.1/16
      
      
        
 